### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by WAG13**

### CODE REVIEW

**Comment by dt-iss** [comment]
Where is your own implementation of functions f(x) and g(x)?

**Comment by WAG13** [comment]
> Where is your own implementation of functions f(x) and g(x)?

FuncF.java and FuncG.java 
I`ve replaced them with functions funcF() and funcG() from lab1.jar 
Should I return my own functions?

**Comment by dt-iss** [comment]
> > Where is your own implementation of functions f(x) and g(x)?
> 
> FuncF.java and FuncG.java
> I`ve replaced them with functions funcF() and funcG() from lab1.jar
> Should I return my own functions?

You should develop your own implementation of functions f(x) and g(x). During the demonstration of your solution you should use your own version of functions and then version from lab1.jar.

**Comment by WAG13** [comment]
> > > Where is your own implementation of functions f(x) and g(x)?
> > 
> > 
> > FuncF.java and FuncG.java
> > I`ve replaced them with functions funcF() and funcG() from lab1.jar
> > Should I return my own functions?
> 
> You should develop your own implementation of functions f(x) and g(x). During the demonstration of your solution you should use your own version of functions and then version from lab1.jar.

Done!

**Review by dt-iss — APPROVED** [review]

**Pull request merged**
